### ISSUE TITLE
OpenUDID privacy problem?

### ISSUE THREAD

**Issue by tomhubina** [ylechelle/OpenUDID#10]
Currently OpenUDID exposes the bundle id and installation time of every application that uses OpenUDID. This seems unnecessary, and adds a significant privacy problem that didn't exist with the old UDID system.

Previously, sharing of information like this was explicit between partners, and typically the only people who had access to this kind of information was the ad networks. Now, any developer would be able to tell which apps are installed on the device, when the app was installed, and if an app was uninstalled (watch it disappear from the pasteboard).

This seems to be a much larger privacy concern than the original UDID ever presented, but it should also be possible to side step it entirely.

If instead of storing the bundle id, a guid was generated by each application (and stored with the application in the prefs) then you would never be able to tell which install was what. The key is that you don't use the same value for each installation of the application.

**Comment by anupamtulsyan** [comment]
I agree, its a major privacy concern if bundle unique identifier is used. This information in no way should be accessible across partners. 

I have changed this and sent a pull request to use guuid instead of bundle id.

**Comment by ylechelle** [comment]
Let's close this issue and discuss in Issue #11
