### ISSUE TITLE
Backup a device and restore it to a new device

### ISSUE THREAD

**Issue by dgutzeit** [ylechelle/OpenUDID#18]
Consider the following scenario:

I have a device with application installed using the OpenUDID.

I do backup of the iOS and then restore it on another device.

What will happen is two devices with the same identifier, no ?

**Comment by ylechelle** [comment]
Correct.
Here, this calls for a signature that uses the MAC address to sign and compare with former, and regenerate the OUDID in that case. Makes sense?

**Comment by ylechelle** [comment]
Please follow-up in Issue #17
