### ISSUE TITLE
New OpenUDIDs generated on each call to [OpenUDID value]

### ISSUE THREAD

**Issue by dkoslow-gs** [ylechelle/OpenUDID#2]
Currently the implementation of [OpenUDID value] generates a new OpenUDID with each call because of two reasons:

1) it fetches data from the pasteboard expecting it to be of type NSDictionary when it is actually stored as NSData. As a result, the check on line 93 to see whether the item returned from the UIPasteboard is of type NSDictionary will always fail. It should instead verify that the item is of type NSData.
2) In the case that there is no data in the OpenUDID pasteboard, the variable dict is not properly initialized to be a new NSMutableDictionary, so nothing ends up getting stored.

The fix to both of these issues is to replace the initialization of dict on line 93 with the following:

<code>NSMutableDictionary\* dict = item && [item isKindOfClass:[NSData class]]
 ? [NSMutableDictionary dictionaryWithDictionary:[NSKeyedUnarchiver unarchiveObjectWithData:item]]
 : [NSMutableDictionary dictionary];
</code>

**Comment by dkoslow-gs** [comment]
Apologies, this was addressed in your bug fix in commit 838a0bdfd1762a4955d4.

**Comment by ylechelle** [comment]
No prob. Thanks for the scrutiny and interest.
