### ISSUE TITLE
Compile error in iOS 4.3

### ISSUE THREAD

**Issue by zdnet** [ylechelle/OpenUDID#21]
dyld: lazy symbol binding failed: Symbol not found: _objc_retainAutoreleasedReturnValue

**Comment by Gavtron** [comment]
I saw this same issue happen when I added OpenUDID to a non-arc project and tried running it on a pre-iOS 5 device. I'm assuming your project is a non-arc project as well, so you're only enabling arc for OpenUDID.

I fixed it by adding "-fobjc-arc" to the Other Linker Flags in the build settings for my app, and then it worked perfectly fine.

Perhaps a comment about this should be added to the "tutorial" part that explains how to enable arc for the file.

**Comment by ikovalisko** [comment]
Agree, could you please add this comment so other guys will have less pain?
