### ISSUE TITLE
Don't force ARC

### ISSUE THREAD

**Issue by jcgsxr** [ylechelle/OpenUDID#24]
I'd like to propose reverting this commit https://github.com/ylechelle/OpenUDID/pull/20, where usage of ARC became a requirement. A number of publishers in our ad network have users who are running on iOS versions 4.2 and below, which causes crash issues for them. Whether or not using ARC is considered the "right way" to do things, this becomes a blocking issue for us as we can't just cut out a portion of our user base. I can only assume that this would also be a blocking issue for others as well who are potentially considering OpenUDID, since we must support all devices and OS versions at the end of the day.

**Comment by ylechelle** [comment]
Please discuss directly there: https://github.com/ylechelle/OpenUDID/pull/12
