### ISSUE TITLE
OpenUDID does not restore the same UDID after updating os and restoring from iCloud

### ISSUE THREAD

**Issue by artemshv** [ylechelle/OpenUDID#27]
It generates new UDID instead of getting old one

**Comment by matiaz** [comment]
is this still happening ? :S

**Comment by jdschmitt** [comment]
I'm seeing the same behavior. Is this only limited to OS upgrades and iCloud restores? Would be nice to get confirmation.

**Comment by matiaz** [comment]
it happens also when you reinstall the app, for example delete your app and install it again, and you will see that behavior.

**Comment by ylechelle** [comment]
If the app in question is the only one supporting OpenUDID on that device/simulator.

**Comment by jdschmitt** [comment]
That's interesting. I was not always seeing the ID change on reinstall but there very well could have been more than one app on the device with OpenUDID.

We are trying to determine if we can rely on this ID to know if an app is uninstalled and reinstalled that it was the same device. Sounds like we can't really rely on that.

**Comment by ylechelle** [comment]
OpenUDID was a great proxy/alternative to UDID (via uniqueIdentifier) pre-iOS 6. Today, you should rely on either IDfA (Identifier for Advertisers) if you're looking for cross-app identification or vendorIdentifier if within the same publisher space. The latter is the most persistent but will not work across apps. If you need to support iOS 5 and below, then you should use OpenUDID for legacy support...

**Comment by albert0m** [comment]
this is still happening. Is there any way to disable the iCloud syncing?
