### ISSUE TITLE
Typo in the diagram showing ARC compiler flag

### ISSUE THREAD

**Issue by timd** [ylechelle/OpenUDID#29]
There's a typo in the Skitch screenshot showing the compiler flags for non-ARC compilation:

https://img.skitch.com/20120411-bcku69k1uw528cwh9frh5px8ya.png

It shows

```
-fnoobjc-arc
```

rather than

```
-fno-objc-arc
```

Not a problem if you've dealt with non-ARC libraries before, but it threw me for a while before I figured it out!

**Comment by adambair** [comment]
+1 Indeed. Thanks, this helped me out.

**Comment by ylechelle** [comment]
indeed
