### ISSUE TITLE
OpenUDID persistence and Potential Crash

### ISSUE THREAD

**Issue by vovagalchenko** [ylechelle/OpenUDID#3]
Hi,

I've looked through the code, as I'm interested in the idea and am considering using openUDID. I have some concerns about it, however, and was wondering if maybe I'm misunderstanding something.
1. Please correct me if I'm wrong, but as far as I understand, a UIPasteboard key-value pair created by an app vanishes when the app is deleted. As far as I understand, that's the purpose of the redundant 100 UIPasteboard slots you've employed. Nevertheless, am I correct in saying that if every OpenUDID-enabled app was removed from a device and then another OpenUDID-enabled app was installed on it, a new unique OpenUDID would be created for that device?
2. Here I'd like to refer to the following code from the + (NSString*) _getOpenUDID function:

// One day, this may no longer be allowed in iOS. When that is, just comment this line out.
    //
# if TARGET_OS_IPHONE

```
_openUDID = [[UIDevice currentDevice] uniqueIdentifier];
```
# endif

If I (and others) were to build OpenUDID into their apps, when Apple discontinues uniqueIdentifier, this will result in a crash. I understand, we can then comment out this line and rebuild the apps and things will work again, but in the meantime, there would be an avalanche of crashes sweeping the OpenUDID-land. Would this not be a more bulletproof solution:

if([UIDevice instancesRespondToSelector:@selector(uniqueIdentifier)]){
        _openUDID = [[UIDevice currentDevice] uniqueIdentifier];
}

I appreciate you working on this problem and let me know what you think if you have time.

vova

**Comment by ylechelle** [comment]
Hello Vova,

Great feedback.

Your analysis is correct. One OpenUDID implementation removed => resets and generates a new OpenUDID. N implementations, and remove them all => also resets. However, remove N-1 implemnatations, and you get persistence. Hence, true persistence is achieved the more OpenUDID is adopted, with an exponential factor. Do you see an alternative to make it more persistent? (apart from using a central cloud-based repository?

Re: the deprecation, I did consider this issue.
For one thing, I believe Apple will not completely remove it, but rather, make it part of the private API.
So the main issue there, I think, is for new apps to be approved with this.

Now, your suggested makes total sense for existing implementations - you never know. Apple _might_ make this call totally unavailable in iOS 6. Better be safe than sorry. I will update the code accordingly.

Best,

Yann.
