### ISSUE TITLE
OpenUDID is not keeping it's value when app is reinstalled on iPhone

### ISSUE THREAD

**Issue by egv** [ylechelle/OpenUDID#32]
I have an application that uses unmodified OpenUDID code. While being constant between application launches OpenUDID changes it's value if I reinstall the application. Is it how it is supposed to work? I am trying this on iPhone 4S, iOS 5.1

**Comment by ylechelle** [comment]
This might be the case if you only have one application using OpenUDID and you remove it. Typically, on a live phone with many apps installed, given the fact that OpenUDID is supported by over 17 ad networks and many individual developers, then the id is likely to be preserved fully.

**Comment by pgorrow** [comment]
Can you explain the mechanics of what happens in this case (what causes the OpenID to change) and how having another app that uses OpenUDID prevents the id from changing during a reinstall?

**Comment by ylechelle** [comment]
The logic is based on replicating the identifier across multiple dedicated pasteboards, the frequency of which ensures persistence and stability in a given device.

**Comment by pgorrow** [comment]
Thanks.  I was unaware of the potential of perserving data via shared UIPasteboards.

**Comment by sujithkris** [comment]
@ylechelle 
Can we conclude that the OpenUDID value will change if the last application having openUDID is uninstalled ?

**Comment by ylechelle** [comment]
Yes, although that is a rare occurrence in real life.
It's often the case in simulator mode.

**Comment by sujithkris** [comment]
@ylechelle 

More question : 
1.Are you using system pasteboard or application pasteboard? 
2. Whether values remains same if we uninstall/reinstall the last app from device, if we use system pasteboard ??
( I am getting different values for unistall/reinstall of last application using OpenUDID)
1. Is Keychain also remove value stored in it if we uninstall the app from device which wrote to keychain ?
