### ISSUE TITLE
OpenUDID value changes on resetting the device

### ISSUE THREAD

**Issue by zeroCoder1** [ylechelle/OpenUDID#33]
I am testing OpenUDID  just by printing it out on a label. I deleted the app and reinstalled it again. The number remained unchanged. But, when I reset the device to the factory settings, and then installed the app again, the number changed. is this faced 

```
NSString * openUDID = [OpenUDID value];
NSLog(@"The value is %@",openUDID);

[idLabel setText:openUDID];
```

I tried uninstalling the app and running it again in the device, the OpenUDID value doesn't change.  However, when you reset the device and run the same app again, the OpenUDID value changes, Am I doing something wrong? Or is this the way it should work.

Please advise.

**Comment by ylechelle** [comment]
Indeed, your use case makes sense. OpenUDID is not hardware based; so if you reset everything, then the id is recreated… if however you restore, then it will most likely be recovered

**Comment by zeroCoder1** [comment]
Thank you for the response. I tried doing that. I reset the device. I restored a backup and the oudid is the same... Thank you for this wonderful idea of using openudid.
