### ISSUE TITLE
Format specifies type 'unsigned int' but the argument has type 'long long'

### ISSUE THREAD

**Issue by ghelton** [ylechelle/OpenUDID#37]
I'm getting a warning where _openUDID is defined:

OpenUDID.m:142:91: _Format specifies type 'unsigned int' but the argument has type 'long long'_

would there be an issue with changing 

arc4random() % 4294967295
to
(NSUInteger)(arc4random() % NSUIntegerMax)

This seems to resolve the issue.

**Comment by ylechelle** [comment]
nice catch
