### ISSUE TITLE
Use id for advertisers?

### ISSUE THREAD

**Issue by pschuegr** [ylechelle/OpenUDID#44]
Any plans to use the new ID for advertisers in iOS6 to underpin this?

**Comment by ylechelle** [comment]
Yes, though I have had absolutely no team to deal with it over the past 6 months… please accept my apologies

**Comment by pschuegr** [comment]
No worries! Just wanted to see if this was something you wanted to move towards.

**Comment by ylechelle** [comment]
Definitely yes
