### ISSUE TITLE
OpenUDID returns the same UDID on different device after backup/restore.

### ISSUE THREAD

**Issue by iriand** [ylechelle/OpenUDID#45]
Getting new device user backups old one and restore data on new one. The same UDID is returned on new and old devices.

**Comment by henrytkirk** [comment]
I can confirm this. I think there are some iDevice management tools out there that do restores of a master profile to multiple (different) devices and it is duplicating the OpenUDID. I noticed this with bulk Educational purchases.

**Comment by matiaz** [comment]
is this still happening ?

**Comment by iriand** [comment]
Yes, it still happenning. It is the major security hole. Applications using OpenUDID can't be sure that device identificator is uniqie.
Is it on the roadmap to fix?

**Comment by ylechelle** [comment]
The strength of the system is that it is standalone and decentralised. Its weakness is that it is decentralized, and therefore no repository can ensure uniqueness. The system is as strong as it gets at scale (i.e. many apps using it across a large user base). The OpenUDID is very close to being unique, really. Collisions are as unlikely as one winning the lottery 10 times in a row... 

That being said, going forward, I urge all to start using the more than desirable IDfA (identifier for advertising) and/or Vendor Identifier. They fulfill all requirements going forward.
