### ISSUE TITLE
RespondToSelector uniqueIdentifier should be removed

### ISSUE THREAD

**Issue by patrickbrennan** [ylechelle/OpenUDID#6]
We are using openUDID as part of a multifaceted solution to UDID deprecation.  In our implementation, we have removed the lines of code I have listed below from the openUDID source files.

This code should be removed from the openSource project for two reasons, A) uniqueIdentifier is deprecated and B) If Apple simply changes the property to no longer send a unique identifier (all 0's or some other non-unique value) but still responds to the property, the openUDID project will not create an openUDID value.    

if([UIDevice instancesRespondToSelector:@selector(uniqueIdentifier)]){
        _openUDID = [[UIDevice currentDevice] uniqueIdentifier];
    }

**Comment by ylechelle** [comment]
Hi Patrick,

THe time has come. THe call has been removed...

Yann
